# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgtestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(502, 398)
        self.centralwidget = QtWidgets.QWidget(ImageViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/img1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.firstimg = QtWidgets.QPushButton(self.centralwidget)
        self.firstimg.setGeometry(QtCore.QRect(50, 300, 131, 31))
        self.firstimg.setObjectName("firstimg")
        self.sec_img = QtWidgets.QPushButton(self.centralwidget)
        self.sec_img.setGeometry(QtCore.QRect(280, 300, 111, 31))
        self.sec_img.setObjectName("sec_img")
        ImageViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 18))
        self.menubar.setObjectName("menubar")
        ImageViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageViewer)
        self.statusbar.setObjectName("statusbar")
        ImageViewer.setStatusBar(self.statusbar)

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

        self.firstimg.clicked.connect(self.img1)
        self.sec_img.clicked.connect(self.img2)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "MainWindow"))
        self.firstimg.setText(_translate("ImageViewer", "show1"))
        self.sec_img.setText(_translate("ImageViewer", "show2"))

    def img1(self):
        self.label.setPixmap(QtGui.QPixmap("img/img1.jpg"))

    def img2(self):
        self.label.setPixmap(QtGui.QPixmap("img/img2.jpg"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageViewer = QtWidgets.QMainWindow()
    ui = Ui_ImageViewer()
    ui.setupUi(ImageViewer)
    ImageViewer.show()
    sys.exit(app.exec_())
