# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testbotUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_desktop_ui(object):
    def setupUi(self, desktop_ui):
        desktop_ui.setObjectName("desktop_ui")
        desktop_ui.resize(730, 493)
        self.centralwidget = QtWidgets.QWidget(desktop_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/bgimg.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 420, 91, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 420, 91, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(88, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 131, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 340, 81, 21))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 340, 81, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 20, 111, 31))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        desktop_ui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(desktop_ui)
        self.statusbar.setObjectName("statusbar")
        desktop_ui.setStatusBar(self.statusbar)

        self.retranslateUi(desktop_ui)
        QtCore.QMetaObject.connectSlotsByName(desktop_ui)

    def retranslateUi(self, desktop_ui):
        _translate = QtCore.QCoreApplication.translate
        desktop_ui.setWindowTitle(_translate("desktop_ui", "MainWindow"))
        self.pushButton.setText(_translate("desktop_ui", "Run"))
        self.pushButton_2.setText(_translate("desktop_ui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    desktop_ui = QtWidgets.QMainWindow()
    ui = Ui_desktop_ui()
    ui.setupUi(desktop_ui)
    desktop_ui.show()
    sys.exit(app.exec_())
